[workspace]
resolver = "2"

members = ["crates/snake_case", "crates/one_log"]

[workspace.dependencies]
clap = { version = "4.4.11", features = [
    "cargo",
    "derive",
    "env",
    "wrap_help",
] }
