[package]
name = "google_slides_speaker_notes_extraction"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
regex.workspace = true
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
